---
# Platform plays
#################
- import_playbook: common.yml


# Service plays
################
- import_playbook: jumpbox.yml
- import_playbook: solr.yml
- import_playbook: redis.yml


# Application plays
####################
- import_playbook: catalog.yml
- import_playbook: dashboard-web.yml
- import_playbook: datagov-web.yml
- import_playbook: inventory.yml
